<?php
/**
 * This defines autoloading handler for whole MediaWiki framework
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 * http://www.gnu.org/copyleft/gpl.html
 *
 * @file
 */

/**
 * Locations of core classes
 * Extension classes are specified with $wgAutoloadClasses
 * This array is a global instead of a static member of AutoLoader to work around a bug in APC
 */
global $wgAutoloadLocalClasses;

$wgAutoloadLocalClasses = array(
	# Includes
	'AjaxDispatcher' => 'wiki/includes/AjaxDispatcher.php',
	'AjaxResponse' => 'wiki/includes/AjaxResponse.php',
	'AlphabeticPager' => 'wiki/includes/Pager.php',
	'Article' => 'wiki/includes/Article.php',
	'AtomFeed' => 'wiki/includes/Feed.php',
	'AuthPlugin' => 'wiki/includes/AuthPlugin.php',
	'AuthPluginUser' => 'wiki/includes/AuthPlugin.php',
	'Autopromote' => 'wiki/includes/Autopromote.php',
	'BaseTemplate' => 'wiki/includes/SkinTemplate.php',
	'Block' => 'wiki/includes/Block.php',
	'CacheHelper' => 'wiki/includes/CacheHelper.php',
	'Category' => 'wiki/includes/Category.php',
	'Categoryfinder' => 'wiki/includes/Categoryfinder.php',
	'CategoryPage' => 'wiki/includes/CategoryPage.php',
	'CategoryViewer' => 'wiki/includes/CategoryViewer.php',
	'ChangesFeed' => 'wiki/includes/ChangesFeed.php',
	'ChangeTags' => 'wiki/includes/ChangeTags.php',
	'ChannelFeed' => 'wiki/includes/Feed.php',
	'Collation' => 'wiki/includes/Collation.php',
	'CollationCkb' => 'wiki/includes/Collation.php',
	'ConcatenatedGzipHistoryBlob' => 'wiki/includes/HistoryBlob.php',
	'Cookie' => 'wiki/includes/Cookie.php',
	'CookieJar' => 'wiki/includes/Cookie.php',
	'CurlHttpRequest' => 'wiki/includes/HttpFunctions.php',
	'DeprecatedGlobal' => 'wiki/includes/DeprecatedGlobal.php',
	'DerivativeRequest' => 'wiki/includes/WebRequest.php',
	'DiffHistoryBlob' => 'wiki/includes/HistoryBlob.php',
	'DummyLinker' => 'wiki/includes/Linker.php',
	'Dump7ZipOutput' => 'wiki/includes/Export.php',
	'DumpBZip2Output' => 'wiki/includes/Export.php',
	'DumpFileOutput' => 'wiki/includes/Export.php',
	'DumpFilter' => 'wiki/includes/Export.php',
	'DumpGZipOutput' => 'wiki/includes/Export.php',
	'DumpLatestFilter' => 'wiki/includes/Export.php',
	'DumpMultiWriter' => 'wiki/includes/Export.php',
	'DumpNamespaceFilter' => 'wiki/includes/Export.php',
	'DumpNotalkFilter' => 'wiki/includes/Export.php',
	'DumpOutput' => 'wiki/includes/Export.php',
	'DumpPipeOutput' => 'wiki/includes/Export.php',
	'EditPage' => 'wiki/includes/EditPage.php',
	'EmailNotification' => 'wiki/includes/UserMailer.php',
	'FakeTitle' => 'wiki/includes/FakeTitle.php',
	'Fallback' => 'wiki/includes/Fallback.php',
	'FauxRequest' => 'wiki/includes/WebRequest.php',
	'FauxResponse' => 'wiki/includes/WebResponse.php',
	'FeedItem' => 'wiki/includes/Feed.php',
	'FeedUtils' => 'wiki/includes/FeedUtils.php',
	'FileDeleteForm' => 'wiki/includes/FileDeleteForm.php',
	'ForkController' => 'wiki/includes/ForkController.php',
	'FormOptions' => 'wiki/includes/FormOptions.php',
	'GitInfo' => 'wiki/includes/GitInfo.php',
	'HistoryBlob' => 'wiki/includes/HistoryBlob.php',
	'HistoryBlobCurStub' => 'wiki/includes/HistoryBlob.php',
	'HistoryBlobStub' => 'wiki/includes/HistoryBlob.php',
	'Hooks' => 'wiki/includes/Hooks.php',
	'Html' => 'wiki/includes/Html.php',
	'HtmlFormatter' => 'wiki/includes/HtmlFormatter.php',
	'HTMLApiField' => 'wiki/includes/htmlform/HTMLApiField.php',
	'HTMLButtonField' => 'wiki/includes/htmlform/HTMLButtonField.php',
	'HTMLCheckField' => 'wiki/includes/htmlform/HTMLCheckField.php',
	'HTMLCheckMatrix' => 'wiki/includes/htmlform/HTMLCheckMatrix.php',
	'HTMLEditTools' => 'wiki/includes/htmlform/HTMLEditTools.php',
	'HTMLFloatField' => 'wiki/includes/htmlform/HTMLFloatField.php',
	'HTMLForm' => 'wiki/includes/htmlform/HTMLForm.php',
	'HTMLFormField' => 'wiki/includes/htmlform/HTMLFormField.php',
	'HTMLFormFieldRequiredOptionsException' =>
		'wiki/includes/htmlform/HTMLFormFieldRequiredOptionsException.php',
	'HTMLHiddenField' => 'wiki/includes/htmlform/HTMLHiddenField.php',
	'HTMLInfoField' => 'wiki/includes/htmlform/HTMLInfoField.php',
	'HTMLIntField' => 'wiki/includes/htmlform/HTMLIntField.php',
	'HTMLNestedFilterable' => 'wiki/includes/htmlform/HTMLNestedFilterable.php',
	'HTMLMultiSelectField' => 'wiki/includes/htmlform/HTMLMultiSelectField.php',
	'HTMLRadioField' => 'wiki/includes/htmlform/HTMLRadioField.php',
	'HTMLSelectAndOtherField' => 'wiki/includes/htmlform/HTMLSelectAndOtherField.php',
	'HTMLSelectField' => 'wiki/includes/htmlform/HTMLSelectField.php',
	'HTMLSelectOrOtherField' => 'wiki/includes/htmlform/HTMLSelectOrOtherField.php',
	'HTMLSubmitField' => 'wiki/includes/htmlform/HTMLSubmitField.php',
	'HTMLTextAreaField' => 'wiki/includes/htmlform/HTMLTextAreaField.php',
	'HTMLTextField' => 'wiki/includes/htmlform/HTMLTextField.php',
	'Http' => 'wiki/includes/HttpFunctions.php',
	'ICacheHelper' => 'wiki/includes/CacheHelper.php',
	'IcuCollation' => 'wiki/includes/Collation.php',
	'IdentityCollation' => 'wiki/includes/Collation.php',
	'ImageHistoryList' => 'wiki/includes/ImagePage.php',
	'ImageHistoryPseudoPager' => 'wiki/includes/ImagePage.php',
	'ImagePage' => 'wiki/includes/ImagePage.php',
	'ImageQueryPage' => 'wiki/includes/ImageQueryPage.php',
	'ImportStreamSource' => 'wiki/includes/Import.php',
	'ImportStringSource' => 'wiki/includes/Import.php',
	'IndexPager' => 'wiki/includes/Pager.php',
	'Interwiki' => 'wiki/includes/interwiki/Interwiki.php',
	'LCStore' => 'wiki/includes/cache/LocalisationCache.php',
	'LCStoreAccel' => 'wiki/includes/cache/LocalisationCache.php',
	'LCStoreCDB' => 'wiki/includes/cache/LocalisationCache.php',
	'LCStoreDB' => 'wiki/includes/cache/LocalisationCache.php',
	'LCStoreNull' => 'wiki/includes/cache/LocalisationCache.php',
	'License' => 'wiki/includes/Licenses.php',
	'Licenses' => 'wiki/includes/Licenses.php',
	'Linker' => 'wiki/includes/Linker.php',
	'LinkFilter' => 'wiki/includes/LinkFilter.php',
	'LocalisationCache' => 'wiki/includes/cache/LocalisationCache.php',
	'LocalisationCacheBulkLoad' => 'wiki/includes/cache/LocalisationCache.php',
	'MagicWord' => 'wiki/includes/MagicWord.php',
	'MagicWordArray' => 'wiki/includes/MagicWord.php',
	'MailAddress' => 'wiki/includes/UserMailer.php',
	'MediaWiki' => 'wiki/includes/Wiki.php',
	'MediaWiki_I18N' => 'wiki/includes/SkinTemplate.php',
	'MediaWikiVersionFetcher' => 'wiki/includes/MediaWikiVersionFetcher.php',
	'Message' => 'wiki/includes/Message.php',
	'MessageBlobStore' => 'wiki/includes/MessageBlobStore.php',
	'MimeMagic' => 'wiki/includes/MimeMagic.php',
	'MWHookException' => 'wiki/includes/Hooks.php',
	'MWHttpRequest' => 'wiki/includes/HttpFunctions.php',
	'MWInit' => 'wiki/includes/Init.php',
	'MWNamespace' => 'wiki/includes/Namespace.php',
	'OutputPage' => 'wiki/includes/OutputPage.php',
	'Page' => 'wiki/includes/WikiPage.php',
	'PageQueryPage' => 'wiki/includes/PageQueryPage.php',
	'Pager' => 'wiki/includes/Pager.php',
	'PasswordError' => 'wiki/includes/User.php',
	'PathRouter' => 'wiki/includes/PathRouter.php',
	'PathRouterPatternReplacer' => 'wiki/includes/PathRouter.php',
	'PhpHttpRequest' => 'wiki/includes/HttpFunctions.php',
	'PoolCounter' => 'wiki/includes/poolcounter/PoolCounter.php',
	'PoolCounter_Stub' => 'wiki/includes/poolcounter/PoolCounter.php',
	'PoolCounterRedis' => 'wiki/includes/poolcounter/PoolCounterRedis.php',
	'PoolCounterWork' => 'wiki/includes/poolcounter/PoolCounterWork.php',
	'PoolCounterWorkViaCallback' => 'wiki/includes/poolcounter/PoolCounterWork.php',
	'PoolWorkArticleView' => 'wiki/includes/WikiPage.php',
	'Preferences' => 'wiki/includes/Preferences.php',
	'PreferencesForm' => 'wiki/includes/Preferences.php',
	'PrefixSearch' => 'wiki/includes/PrefixSearch.php',
	'ProtectionForm' => 'wiki/includes/ProtectionForm.php',
	'QueryPage' => 'wiki/includes/QueryPage.php',
	'QuickTemplate' => 'wiki/includes/SkinTemplate.php',
	'RawMessage' => 'wiki/includes/Message.php',
	'ReverseChronologicalPager' => 'wiki/includes/Pager.php',
	'RevisionItem' => 'wiki/includes/RevisionList.php',
	'RevisionItemBase' => 'wiki/includes/RevisionList.php',
	'RevisionListBase' => 'wiki/includes/RevisionList.php',
	'Revision' => 'wiki/includes/Revision.php',
	'RevisionList' => 'wiki/includes/RevisionList.php',
	'RSSFeed' => 'wiki/includes/Feed.php',
	'Sanitizer' => 'wiki/includes/Sanitizer.php',
	'SiteConfiguration' => 'wiki/includes/SiteConfiguration.php',
	'SiteStats' => 'wiki/includes/SiteStats.php',
	'SiteStatsInit' => 'wiki/includes/SiteStats.php',
	'Skin' => 'wiki/includes/Skin.php',
	'SkinTemplate' => 'wiki/includes/SkinTemplate.php',
	'SquidPurgeClient' => 'wiki/includes/SquidPurgeClient.php',
	'SquidPurgeClientPool' => 'wiki/includes/SquidPurgeClient.php',
	'StatCounter' => 'wiki/includes/StatCounter.php',
	'Status' => 'wiki/includes/Status.php',
	'StreamFile' => 'wiki/includes/StreamFile.php',
	'StringPrefixSearch' => 'wiki/includes/PrefixSearch.php',
	'StubContLang' => 'wiki/includes/StubObject.php',
	'StubObject' => 'wiki/includes/StubObject.php',
	'StubUserLang' => 'wiki/includes/StubObject.php',
	'TablePager' => 'wiki/includes/Pager.php',
	'MWTimestamp' => 'wiki/includes/MWTimestamp.php',
	'TimestampException' => 'wiki/includes/TimestampException.php',
	'Title' => 'wiki/includes/Title.php',
	'TitleArray' => 'wiki/includes/TitleArray.php',
	'TitleArrayFromResult' => 'wiki/includes/TitleArrayFromResult.php',
	'TitlePrefixSearch' => 'wiki/includes/PrefixSearch.php',
	'UploadSourceAdapter' => 'wiki/includes/Import.php',
	'UppercaseCollation' => 'wiki/includes/Collation.php',
	'User' => 'wiki/includes/User.php',
	'UserArray' => 'wiki/includes/UserArray.php',
	'UserArrayFromResult' => 'wiki/includes/UserArrayFromResult.php',
	'UserCache' => 'wiki/includes/cache/UserCache.php',
	'UserMailer' => 'wiki/includes/UserMailer.php',
	'UserRightsProxy' => 'wiki/includes/UserRightsProxy.php',
	'WantedQueryPage' => 'wiki/includes/QueryPage.php',
	'WatchedItem' => 'wiki/includes/WatchedItem.php',
	'WebRequest' => 'wiki/includes/WebRequest.php',
	'WebRequestUpload' => 'wiki/includes/WebRequest.php',
	'WebResponse' => 'wiki/includes/WebResponse.php',
	'WikiCategoryPage' => 'wiki/includes/WikiCategoryPage.php',
	'WikiExporter' => 'wiki/includes/Export.php',
	'WikiFilePage' => 'wiki/includes/WikiFilePage.php',
	'WikiImporter' => 'wiki/includes/Import.php',
	'WikiPage' => 'wiki/includes/WikiPage.php',
	'WikiRevision' => 'wiki/includes/Import.php',
	'WikiMap' => 'wiki/includes/WikiMap.php',
	'WikiReference' => 'wiki/includes/WikiMap.php',
	'Xml' => 'wiki/includes/Xml.php',
	'XmlDumpWriter' => 'wiki/includes/Export.php',
	'XmlJsCode' => 'wiki/includes/Xml.php',
	'XMLReader2' => 'wiki/includes/Import.php',
	'XmlSelect' => 'wiki/includes/Xml.php',

	# wiki/includes/actions
	'Action' => 'wiki/includes/actions/Action.php',
	'CachedAction' => 'wiki/includes/actions/CachedAction.php',
	'CreditsAction' => 'wiki/includes/actions/CreditsAction.php',
	'DeleteAction' => 'wiki/includes/actions/DeleteAction.php',
	'EditAction' => 'wiki/includes/actions/EditAction.php',
	'FormlessAction' => 'wiki/includes/actions/FormlessAction.php',
	'FormAction' => 'wiki/includes/actions/FormAction.php',
	'HistoryAction' => 'wiki/includes/actions/HistoryAction.php',
	'HistoryPage' => 'wiki/includes/actions/HistoryAction.php',
	'HistoryPager' => 'wiki/includes/actions/HistoryAction.php',
	'InfoAction' => 'wiki/includes/actions/InfoAction.php',
	'MarkpatrolledAction' => 'wiki/includes/actions/MarkpatrolledAction.php',
	'ProtectAction' => 'wiki/includes/actions/ProtectAction.php',
	'PurgeAction' => 'wiki/includes/actions/PurgeAction.php',
	'RawAction' => 'wiki/includes/actions/RawAction.php',
	'RawPage' => 'wiki/includes/actions/RawAction.php',
	'RenderAction' => 'wiki/includes/actions/RenderAction.php',
	'RevertAction' => 'wiki/includes/actions/RevertAction.php',
	'RevertFileAction' => 'wiki/includes/actions/RevertAction.php',
	'RevisiondeleteAction' => 'wiki/includes/actions/RevisiondeleteAction.php',
	'RollbackAction' => 'wiki/includes/actions/RollbackAction.php',
	'SubmitAction' => 'wiki/includes/actions/EditAction.php',
	'UnprotectAction' => 'wiki/includes/actions/ProtectAction.php',
	'UnwatchAction' => 'wiki/includes/actions/WatchAction.php',
	'ViewAction' => 'wiki/includes/actions/ViewAction.php',
	'WatchAction' => 'wiki/includes/actions/WatchAction.php',

	# wiki/includes/api
	'ApiBase' => 'wiki/includes/api/ApiBase.php',
	'ApiBlock' => 'wiki/includes/api/ApiBlock.php',
	'ApiComparePages' => 'wiki/includes/api/ApiComparePages.php',
	'ApiCreateAccount' => 'wiki/includes/api/ApiCreateAccount.php',
	'ApiDelete' => 'wiki/includes/api/ApiDelete.php',
	'ApiDisabled' => 'wiki/includes/api/ApiDisabled.php',
	'ApiEditPage' => 'wiki/includes/api/ApiEditPage.php',
	'ApiEmailUser' => 'wiki/includes/api/ApiEmailUser.php',
	'ApiExpandTemplates' => 'wiki/includes/api/ApiExpandTemplates.php',
	'ApiFeedContributions' => 'wiki/includes/api/ApiFeedContributions.php',
	'ApiFeedRecentChanges' => 'wiki/includes/api/ApiFeedRecentChanges.php',
	'ApiFeedWatchlist' => 'wiki/includes/api/ApiFeedWatchlist.php',
	'ApiFileRevert' => 'wiki/includes/api/ApiFileRevert.php',
	'ApiFormatBase' => 'wiki/includes/api/ApiFormatBase.php',
	'ApiFormatDbg' => 'wiki/includes/api/ApiFormatDbg.php',
	'ApiFormatDump' => 'wiki/includes/api/ApiFormatDump.php',
	'ApiFormatFeedWrapper' => 'wiki/includes/api/ApiFormatBase.php',
	'ApiFormatJson' => 'wiki/includes/api/ApiFormatJson.php',
	'ApiFormatNone' => 'wiki/includes/api/ApiFormatNone.php',
	'ApiFormatPhp' => 'wiki/includes/api/ApiFormatPhp.php',
	'ApiFormatRaw' => 'wiki/includes/api/ApiFormatRaw.php',
	'ApiFormatTxt' => 'wiki/includes/api/ApiFormatTxt.php',
	'ApiFormatWddx' => 'wiki/includes/api/ApiFormatWddx.php',
	'ApiFormatXml' => 'wiki/includes/api/ApiFormatXml.php',
	'ApiFormatXmlRsd' => 'wiki/includes/api/ApiRsd.php',
	'ApiFormatYaml' => 'wiki/includes/api/ApiFormatYaml.php',
	'ApiHelp' => 'wiki/includes/api/ApiHelp.php',
	'ApiImageRotate' => 'wiki/includes/api/ApiImageRotate.php',
	'ApiImport' => 'wiki/includes/api/ApiImport.php',
	'ApiImportReporter' => 'wiki/includes/api/ApiImport.php',
	'ApiLogin' => 'wiki/includes/api/ApiLogin.php',
	'ApiLogout' => 'wiki/includes/api/ApiLogout.php',
	'ApiMain' => 'wiki/includes/api/ApiMain.php',
	'ApiModuleManager' => 'wiki/includes/api/ApiModuleManager.php',
	'ApiMove' => 'wiki/includes/api/ApiMove.php',
	'ApiOpenSearch' => 'wiki/includes/api/ApiOpenSearch.php',
	'ApiOptions' => 'wiki/includes/api/ApiOptions.php',
	'ApiPageSet' => 'wiki/includes/api/ApiPageSet.php',
	'ApiParamInfo' => 'wiki/includes/api/ApiParamInfo.php',
	'ApiParse' => 'wiki/includes/api/ApiParse.php',
	'ApiPatrol' => 'wiki/includes/api/ApiPatrol.php',
	'ApiProtect' => 'wiki/includes/api/ApiProtect.php',
	'ApiPurge' => 'wiki/includes/api/ApiPurge.php',
	'ApiQuery' => 'wiki/includes/api/ApiQuery.php',
	'ApiQueryAllCategories' => 'wiki/includes/api/ApiQueryAllCategories.php',
	'ApiQueryAllImages' => 'wiki/includes/api/ApiQueryAllImages.php',
	'ApiQueryAllLinks' => 'wiki/includes/api/ApiQueryAllLinks.php',
	'ApiQueryAllMessages' => 'wiki/includes/api/ApiQueryAllMessages.php',
	'ApiQueryAllPages' => 'wiki/includes/api/ApiQueryAllPages.php',
	'ApiQueryAllUsers' => 'wiki/includes/api/ApiQueryAllUsers.php',
	'ApiQueryBacklinks' => 'wiki/includes/api/ApiQueryBacklinks.php',
	'ApiQueryBase' => 'wiki/includes/api/ApiQueryBase.php',
	'ApiQueryBlocks' => 'wiki/includes/api/ApiQueryBlocks.php',
	'ApiQueryCategories' => 'wiki/includes/api/ApiQueryCategories.php',
	'ApiQueryCategoryInfo' => 'wiki/includes/api/ApiQueryCategoryInfo.php',
	'ApiQueryCategoryMembers' => 'wiki/includes/api/ApiQueryCategoryMembers.php',
	'ApiQueryContributions' => 'wiki/includes/api/ApiQueryUserContributions.php',
	'ApiQueryContributors' => 'wiki/includes/api/ApiQueryContributors.php',
	'ApiQueryDeletedrevs' => 'wiki/includes/api/ApiQueryDeletedrevs.php',
	'ApiQueryDisabled' => 'wiki/includes/api/ApiQueryDisabled.php',
	'ApiQueryDuplicateFiles' => 'wiki/includes/api/ApiQueryDuplicateFiles.php',
	'ApiQueryExternalLinks' => 'wiki/includes/api/ApiQueryExternalLinks.php',
	'ApiQueryExtLinksUsage' => 'wiki/includes/api/ApiQueryExtLinksUsage.php',
	'ApiQueryFilearchive' => 'wiki/includes/api/ApiQueryFilearchive.php',
	'ApiQueryGeneratorBase' => 'wiki/includes/api/ApiQueryBase.php',
	'ApiQueryImageInfo' => 'wiki/includes/api/ApiQueryImageInfo.php',
	'ApiQueryImages' => 'wiki/includes/api/ApiQueryImages.php',
	'ApiQueryInfo' => 'wiki/includes/api/ApiQueryInfo.php',
	'ApiQueryIWBacklinks' => 'wiki/includes/api/ApiQueryIWBacklinks.php',
	'ApiQueryIWLinks' => 'wiki/includes/api/ApiQueryIWLinks.php',
	'ApiQueryLangBacklinks' => 'wiki/includes/api/ApiQueryLangBacklinks.php',
	'ApiQueryLangLinks' => 'wiki/includes/api/ApiQueryLangLinks.php',
	'ApiQueryLinks' => 'wiki/includes/api/ApiQueryLinks.php',
	'ApiQueryLogEvents' => 'wiki/includes/api/ApiQueryLogEvents.php',
	'ApiQueryORM' => 'wiki/includes/api/ApiQueryORM.php',
	'ApiQueryPageProps' => 'wiki/includes/api/ApiQueryPageProps.php',
	'ApiQueryPagesWithProp' => 'wiki/includes/api/ApiQueryPagesWithProp.php',
	'ApiQueryPagePropNames' => 'wiki/includes/api/ApiQueryPagePropNames.php',
	'ApiQueryPrefixSearch' => 'wiki/includes/api/ApiQueryPrefixSearch.php',
	'ApiQueryProtectedTitles' => 'wiki/includes/api/ApiQueryProtectedTitles.php',
	'ApiQueryQueryPage' => 'wiki/includes/api/ApiQueryQueryPage.php',
	'ApiQueryRandom' => 'wiki/includes/api/ApiQueryRandom.php',
	'ApiQueryRecentChanges' => 'wiki/includes/api/ApiQueryRecentChanges.php',
	'ApiQueryFileRepoInfo' => 'wiki/includes/api/ApiQueryFileRepoInfo.php',
	'ApiQueryRedirects' => 'wiki/includes/api/ApiQueryRedirects.php',
	'ApiQueryRevisions' => 'wiki/includes/api/ApiQueryRevisions.php',
	'ApiQuerySearch' => 'wiki/includes/api/ApiQuerySearch.php',
	'ApiQuerySiteinfo' => 'wiki/includes/api/ApiQuerySiteinfo.php',
	'ApiQueryStashImageInfo' => 'wiki/includes/api/ApiQueryStashImageInfo.php',
	'ApiQueryTags' => 'wiki/includes/api/ApiQueryTags.php',
	'ApiQueryUserInfo' => 'wiki/includes/api/ApiQueryUserInfo.php',
	'ApiQueryUsers' => 'wiki/includes/api/ApiQueryUsers.php',
	'ApiQueryWatchlist' => 'wiki/includes/api/ApiQueryWatchlist.php',
	'ApiQueryWatchlistRaw' => 'wiki/includes/api/ApiQueryWatchlistRaw.php',
	'ApiResult' => 'wiki/includes/api/ApiResult.php',
	'ApiRevisionDelete' => 'wiki/includes/api/ApiRevisionDelete.php',
	'ApiRollback' => 'wiki/includes/api/ApiRollback.php',
	'ApiRsd' => 'wiki/includes/api/ApiRsd.php',
	'ApiSetNotificationTimestamp' => 'wiki/includes/api/ApiSetNotificationTimestamp.php',
	'ApiTokens' => 'wiki/includes/api/ApiTokens.php',
	'ApiUnblock' => 'wiki/includes/api/ApiUnblock.php',
	'ApiUndelete' => 'wiki/includes/api/ApiUndelete.php',
	'ApiUpload' => 'wiki/includes/api/ApiUpload.php',
	'ApiUserrights' => 'wiki/includes/api/ApiUserrights.php',
	'ApiWatch' => 'wiki/includes/api/ApiWatch.php',
	'UsageException' => 'wiki/includes/api/ApiMain.php',

	# wiki/includes/cache
	'BacklinkCache' => 'wiki/includes/cache/BacklinkCache.php',
	'CacheDependency' => 'wiki/includes/cache/CacheDependency.php',
	'ConstantDependency' => 'wiki/includes/cache/CacheDependency.php',
	'DependencyWrapper' => 'wiki/includes/cache/CacheDependency.php',
	'FileCacheBase' => 'wiki/includes/cache/FileCacheBase.php',
	'FileDependency' => 'wiki/includes/cache/CacheDependency.php',
	'GenderCache' => 'wiki/includes/cache/GenderCache.php',
	'GlobalDependency' => 'wiki/includes/cache/CacheDependency.php',
	'HTMLFileCache' => 'wiki/includes/cache/HTMLFileCache.php',
	'LinkBatch' => 'wiki/includes/cache/LinkBatch.php',
	'LinkCache' => 'wiki/includes/cache/LinkCache.php',
	'MapCacheLRU' => 'wiki/includes/cache/MapCacheLRU.php',
	'MessageCache' => 'wiki/includes/cache/MessageCache.php',
	'ObjectFileCache' => 'wiki/includes/cache/ObjectFileCache.php',
	'ResourceFileCache' => 'wiki/includes/cache/ResourceFileCache.php',

	# wiki/includes/changes
	'ChangesList' => 'wiki/includes/changes/ChangesList.php',
	'EnhancedChangesList' => 'wiki/includes/changes/EnhancedChangesList.php',
	'OldChangesList' => 'wiki/includes/changes/OldChangesList.php',
	'RCCacheEntry' => 'wiki/includes/changes/RCCacheEntry.php',
	'RCCacheEntryFactory' => 'wiki/includes/changes/RCCacheEntryFactory.php',
	'RecentChange' => 'wiki/includes/changes/RecentChange.php',

	# wiki/includes/clientpool
	'RedisConnectionPool' => 'wiki/includes/clientpool/RedisConnectionPool.php',
	'RedisConnRef' => 'wiki/includes/clientpool/RedisConnectionPool.php',

	# wiki/includes/composer
	'ComposerPackageModifier' => 'wiki/includes/composer/ComposerPackageModifier.php',
	'ComposerVersionNormalizer' => 'wiki/includes/composer/ComposerVersionNormalizer.php',

	# wiki/includes/config
	'Config' => 'wiki/includes/config/Config.php',
	'ConfigException' => 'wiki/includes/config/ConfigException.php',
	'ConfigFactory' => 'wiki/includes/config/ConfigFactory.php',
	'GlobalVarConfig' => 'wiki/includes/config/GlobalVarConfig.php',

	# wiki/includes/content
	'AbstractContent' => 'wiki/includes/content/AbstractContent.php',
	'ContentHandler' => 'wiki/includes/content/ContentHandler.php',
	'Content' => 'wiki/includes/content/Content.php',
	'CssContentHandler' => 'wiki/includes/content/CssContentHandler.php',
	'CssContent' => 'wiki/includes/content/CssContent.php',
	'JavaScriptContentHandler' => 'wiki/includes/content/JavaScriptContentHandler.php',
	'JavaScriptContent' => 'wiki/includes/content/JavaScriptContent.php',
	'MessageContent' => 'wiki/includes/content/MessageContent.php',
	'MWContentSerializationException' => 'wiki/includes/content/ContentHandler.php',
	'TextContentHandler' => 'wiki/includes/content/TextContentHandler.php',
	'TextContent' => 'wiki/includes/content/TextContent.php',
	'WikitextContentHandler' => 'wiki/includes/content/WikitextContentHandler.php',
	'WikitextContent' => 'wiki/includes/content/WikitextContent.php',

	# wiki/includes/context
	'ContextSource' => 'wiki/includes/context/ContextSource.php',
	'DerivativeContext' => 'wiki/includes/context/DerivativeContext.php',
	'IContextSource' => 'wiki/includes/context/IContextSource.php',
	'RequestContext' => 'wiki/includes/context/RequestContext.php',

	# wiki/includes/dao
	'IDBAccessObject' => 'wiki/includes/dao/IDBAccessObject.php',
	'DBAccessBase' => 'wiki/includes/dao/DBAccessBase.php',

	# wiki/includes/db
	'Blob' => 'wiki/includes/db/DatabaseUtility.php',
	'ChronologyProtector' => 'wiki/includes/db/ChronologyProtector.php',
	'CloneDatabase' => 'wiki/includes/db/CloneDatabase.php',
	'DatabaseBase' => 'wiki/includes/db/Database.php',
	'DatabaseMssql' => 'wiki/includes/db/DatabaseMssql.php',
	'DatabaseMysql' => 'wiki/includes/db/DatabaseMysql.php',
	'DatabaseMysqlBase' => 'wiki/includes/db/DatabaseMysqlBase.php',
	'DatabaseMysqli' => 'wiki/includes/db/DatabaseMysqli.php',
	'DatabaseOracle' => 'wiki/includes/db/DatabaseOracle.php',
	'DatabasePostgres' => 'wiki/includes/db/DatabasePostgres.php',
	'DatabaseSqlite' => 'wiki/includes/db/DatabaseSqlite.php',
	'DatabaseSqliteStandalone' => 'wiki/includes/db/DatabaseSqlite.php',
	'DatabaseType' => 'wiki/includes/db/Database.php',
	'DBAccessError' => 'wiki/includes/db/LBFactory.php',
	'DBConnectionError' => 'wiki/includes/db/DatabaseError.php',
	'DBConnRef' => 'wiki/includes/db/LoadBalancer.php',
	'DBError' => 'wiki/includes/db/DatabaseError.php',
	'DBExpectedError' => 'wiki/includes/db/DatabaseError.php',
	'DBObject' => 'wiki/includes/db/DatabaseUtility.php',
	'IDatabase'  => 'wiki/includes/db/Database.php',
	'IORMRow' => 'wiki/includes/db/IORMRow.php',
	'IORMTable' => 'wiki/includes/db/IORMTable.php',
	'DBMasterPos' => 'wiki/includes/db/DatabaseUtility.php',
	'DBQueryError' => 'wiki/includes/db/DatabaseError.php',
	'DBUnexpectedError' => 'wiki/includes/db/DatabaseError.php',
	'FakeResultWrapper' => 'wiki/includes/db/DatabaseUtility.php',
	'Field' => 'wiki/includes/db/DatabaseUtility.php',
	'LBFactory' => 'wiki/includes/db/LBFactory.php',
	'LBFactoryFake' => 'wiki/includes/db/LBFactory.php',
	'LBFactoryMulti' => 'wiki/includes/db/LBFactoryMulti.php',
	'LBFactorySimple' => 'wiki/includes/db/LBFactory.php',
	'LBFactorySingle' => 'wiki/includes/db/LBFactorySingle.php',
	'LikeMatch' => 'wiki/includes/db/DatabaseUtility.php',
	'LoadBalancer' => 'wiki/includes/db/LoadBalancer.php',
	'LoadBalancerSingle' => 'wiki/includes/db/LBFactorySingle.php',
	'LoadMonitor' => 'wiki/includes/db/LoadMonitor.php',
	'LoadMonitorMySQL' => 'wiki/includes/db/LoadMonitor.php',
	'LoadMonitorNull' => 'wiki/includes/db/LoadMonitor.php',
	'MssqlField' => 'wiki/includes/db/DatabaseMssql.php',
	'MssqlBlob' => 'wiki/includes/db/DatabaseMssql.php',
	'MssqlResultWrapper' => 'wiki/includes/db/DatabaseMssql.php',
	'MySQLField' => 'wiki/includes/db/DatabaseMysqlBase.php',
	'MySQLMasterPos' => 'wiki/includes/db/DatabaseMysqlBase.php',
	'ORAField' => 'wiki/includes/db/DatabaseOracle.php',
	'ORAResult' => 'wiki/includes/db/DatabaseOracle.php',
	'ORMIterator' => 'wiki/includes/db/ORMIterator.php',
	'ORMResult' => 'wiki/includes/db/ORMResult.php',
	'ORMRow' => 'wiki/includes/db/ORMRow.php',
	'ORMTable' => 'wiki/includes/db/ORMTable.php',
	'PostgresField' => 'wiki/includes/db/DatabasePostgres.php',
	'PostgresTransactionState' => 'wiki/includes/db/DatabasePostgres.php',
	'ResultWrapper' => 'wiki/includes/db/DatabaseUtility.php',
	'SavepointPostgres' => 'wiki/includes/db/DatabasePostgres.php',
	'SQLiteField' => 'wiki/includes/db/DatabaseSqlite.php',

	# wiki/includes/debug
	'MWDebug' => 'wiki/includes/debug/Debug.php',

	# wiki/includes/deferred
	'DataUpdate' => 'wiki/includes/deferred/DataUpdate.php',
	'DeferrableUpdate' => 'wiki/includes/deferred/DeferredUpdates.php',
	'DeferredUpdates' => 'wiki/includes/deferred/DeferredUpdates.php',
	'HTMLCacheUpdate' => 'wiki/includes/deferred/HTMLCacheUpdate.php',
	'LinksDeletionUpdate' => 'wiki/includes/deferred/LinksUpdate.php',
	'LinksUpdate' => 'wiki/includes/deferred/LinksUpdate.php',
	'MWCallableUpdate' => 'wiki/includes/deferred/CallableUpdate.php',
	'SearchUpdate' => 'wiki/includes/deferred/SearchUpdate.php',
	'SiteStatsUpdate' => 'wiki/includes/deferred/SiteStatsUpdate.php',
	'SqlDataUpdate' => 'wiki/includes/deferred/SqlDataUpdate.php',
	'SquidUpdate' => 'wiki/includes/deferred/SquidUpdate.php',
	'ViewCountUpdate' => 'wiki/includes/deferred/ViewCountUpdate.php',

	# wiki/includes/diff
	'DiffEngine' => 'wiki/includes/diff/DairikiDiff.php',
	'DiffOp' => 'wiki/includes/diff/DairikiDiff.php',
	'DiffOpAdd' => 'wiki/includes/diff/DairikiDiff.php',
	'DiffOpChange' => 'wiki/includes/diff/DairikiDiff.php',
	'DiffOpCopy' => 'wiki/includes/diff/DairikiDiff.php',
	'DiffOpDelete' => 'wiki/includes/diff/DairikiDiff.php',
	'HWLDFWordAccumulator' => 'wiki/includes/diff/DairikiDiff.php',
	'ArrayDiffFormatter' => 'wiki/includes/diff/ArrayDiffFormatter.php',
	'Diff' => 'wiki/includes/diff/DairikiDiff.php',
	'DifferenceEngine' => 'wiki/includes/diff/DifferenceEngine.php',
	'DiffFormatter' => 'wiki/includes/diff/DiffFormatter.php',
	'MappedDiff' => 'wiki/includes/diff/DairikiDiff.php',
	'RangeDifference' => 'wiki/includes/diff/WikiDiff3.php',
	'TableDiffFormatter' => 'wiki/includes/diff/TableDiffFormatter.php',
	'UnifiedDiffFormatter' => 'wiki/includes/diff/UnifiedDiffFormatter.php',
	'WikiDiff3' => 'wiki/includes/diff/WikiDiff3.php',
	'WordLevelDiff' => 'wiki/includes/diff/DairikiDiff.php',

	# wiki/includes/exception
	'UserBlockedError' => 'wiki/includes/exception/UserBlockedError.php',
	'UserNotLoggedIn' => 'wiki/includes/exception/UserNotLoggedIn.php',
	'ThrottledError' => 'wiki/includes/exception/ThrottledError.php',
	'ReadOnlyError' => 'wiki/includes/exception/ReadOnlyError.php',
	'PermissionsError' => 'wiki/includes/exception/PermissionsError.php',
	'MWException' => 'wiki/includes/exception/MWException.php',
	'MWExceptionHandler' => 'wiki/includes/exception/MWExceptionHandler.php',
	'HttpError' => 'wiki/includes/exception/HttpError.php',
	'BadTitleError' => 'wiki/includes/exception/BadTitleError.php',
	'ErrorPageError' => 'wiki/includes/exception/ErrorPageError.php',
	'FatalError' => 'wiki/includes/exception/FatalError.php',

	# wiki/includes/externalstore
	'ExternalStore' => 'wiki/includes/externalstore/ExternalStore.php',
	'ExternalStoreDB' => 'wiki/includes/externalstore/ExternalStoreDB.php',
	'ExternalStoreHttp' => 'wiki/includes/externalstore/ExternalStoreHttp.php',
	'ExternalStoreMedium' => 'wiki/includes/externalstore/ExternalStoreMedium.php',
	'ExternalStoreMwstore' => 'wiki/includes/externalstore/ExternalStoreMwstore.php',

	# wiki/includes/filebackend
	'FileBackendGroup' => 'wiki/includes/filebackend/FileBackendGroup.php',
	'FileBackend' => 'wiki/includes/filebackend/FileBackend.php',
	'FileBackendError' => 'wiki/includes/filebackend/FileBackend.php',
	'FileBackendException' => 'wiki/includes/filebackend/FileBackend.php',
	'FileBackendStore' => 'wiki/includes/filebackend/FileBackendStore.php',
	'FileBackendStoreShardListIterator' => 'wiki/includes/filebackend/FileBackendStore.php',
	'FileBackendStoreShardDirIterator' => 'wiki/includes/filebackend/FileBackendStore.php',
	'FileBackendStoreShardFileIterator' => 'wiki/includes/filebackend/FileBackendStore.php',
	'FileBackendMultiWrite' => 'wiki/includes/filebackend/FileBackendMultiWrite.php',
	'FileBackendStoreOpHandle' => 'wiki/includes/filebackend/FileBackendStore.php',
	'FSFile' => 'wiki/includes/filebackend/FSFile.php',
	'FSFileBackend' => 'wiki/includes/filebackend/FSFileBackend.php',
	'FSFileBackendList' => 'wiki/includes/filebackend/FSFileBackend.php',
	'FSFileBackendDirList' => 'wiki/includes/filebackend/FSFileBackend.php',
	'FSFileBackendFileList' => 'wiki/includes/filebackend/FSFileBackend.php',
	'FSFileOpHandle' => 'wiki/includes/filebackend/FSFileBackend.php',
	'MemoryFileBackend' => 'wiki/includes/filebackend/MemoryFileBackend.php',
	'SwiftFileBackend' => 'wiki/includes/filebackend/SwiftFileBackend.php',
	'SwiftFileBackendList' => 'wiki/includes/filebackend/SwiftFileBackend.php',
	'SwiftFileBackendDirList' => 'wiki/includes/filebackend/SwiftFileBackend.php',
	'SwiftFileBackendFileList' => 'wiki/includes/filebackend/SwiftFileBackend.php',
	'SwiftFileOpHandle' => 'wiki/includes/filebackend/SwiftFileBackend.php',
	'TempFSFile' => 'wiki/includes/filebackend/TempFSFile.php',
	'FileJournal' => 'wiki/includes/filebackend/filejournal/FileJournal.php',
	'DBFileJournal' => 'wiki/includes/filebackend/filejournal/DBFileJournal.php',
	'NullFileJournal' => 'wiki/includes/filebackend/filejournal/FileJournal.php',
	'LockManagerGroup' => 'wiki/includes/filebackend/lockmanager/LockManagerGroup.php',
	'LockManager' => 'wiki/includes/filebackend/lockmanager/LockManager.php',
	'ScopedLock' => 'wiki/includes/filebackend/lockmanager/ScopedLock.php',
	'FSLockManager' => 'wiki/includes/filebackend/lockmanager/FSLockManager.php',
	'DBLockManager' => 'wiki/includes/filebackend/lockmanager/DBLockManager.php',
	'MemcLockManager' => 'wiki/includes/filebackend/lockmanager/MemcLockManager.php',
	'QuorumLockManager' => 'wiki/includes/filebackend/lockmanager/QuorumLockManager.php',
	'MySqlLockManager' => 'wiki/includes/filebackend/lockmanager/DBLockManager.php',
	'PostgreSqlLockManager' => 'wiki/includes/filebackend/lockmanager/DBLockManager.php',
	'RedisLockManager' => 'wiki/includes/filebackend/lockmanager/RedisLockManager.php',
	'NullLockManager' => 'wiki/includes/filebackend/lockmanager/LockManager.php',
	'FileOp' => 'wiki/includes/filebackend/FileOp.php',
	'FileOpBatch' => 'wiki/includes/filebackend/FileOpBatch.php',
	'StoreFileOp' => 'wiki/includes/filebackend/FileOp.php',
	'CopyFileOp' => 'wiki/includes/filebackend/FileOp.php',
	'MoveFileOp' => 'wiki/includes/filebackend/FileOp.php',
	'DeleteFileOp' => 'wiki/includes/filebackend/FileOp.php',
	'CreateFileOp' => 'wiki/includes/filebackend/FileOp.php',
	'DescribeFileOp' => 'wiki/includes/filebackend/FileOp.php',
	'NullFileOp' => 'wiki/includes/filebackend/FileOp.php',

	# wiki/includes/filerepo
	'FileRepo' => 'wiki/includes/filerepo/FileRepo.php',
	'FileRepoStatus' => 'wiki/includes/filerepo/FileRepoStatus.php',
	'ForeignAPIRepo' => 'wiki/includes/filerepo/ForeignAPIRepo.php',
	'ForeignDBRepo' => 'wiki/includes/filerepo/ForeignDBRepo.php',
	'ForeignDBViaLBRepo' => 'wiki/includes/filerepo/ForeignDBViaLBRepo.php',
	'FSRepo' => 'wiki/includes/filerepo/FSRepo.php',
	'LocalRepo' => 'wiki/includes/filerepo/LocalRepo.php',
	'NullRepo' => 'wiki/includes/filerepo/NullRepo.php',
	'RepoGroup' => 'wiki/includes/filerepo/RepoGroup.php',
	'TempFileRepo' => 'wiki/includes/filerepo/FileRepo.php',

	# wiki/includes/filerepo/file
	'ArchivedFile' => 'wiki/includes/filerepo/file/ArchivedFile.php',
	'File' => 'wiki/includes/filerepo/file/File.php',
	'ForeignAPIFile' => 'wiki/includes/filerepo/file/ForeignAPIFile.php',
	'ForeignDBFile' => 'wiki/includes/filerepo/file/ForeignDBFile.php',
	'LocalFile' => 'wiki/includes/filerepo/file/LocalFile.php',
	'LocalFileDeleteBatch' => 'wiki/includes/filerepo/file/LocalFile.php',
	'LocalFileMoveBatch' => 'wiki/includes/filerepo/file/LocalFile.php',
	'LocalFileRestoreBatch' => 'wiki/includes/filerepo/file/LocalFile.php',
	'OldLocalFile' => 'wiki/includes/filerepo/file/OldLocalFile.php',
	'UnregisteredLocalFile' => 'wiki/includes/filerepo/file/UnregisteredLocalFile.php',

	# wiki/includes/installer
	'CliInstaller' => 'wiki/includes/installer/CliInstaller.php',
	'DatabaseInstaller' => 'wiki/includes/installer/DatabaseInstaller.php',
	'DatabaseUpdater' => 'wiki/includes/installer/DatabaseUpdater.php',
	'InstallDocFormatter' => 'wiki/includes/installer/InstallDocFormatter.php',
	'Installer' => 'wiki/includes/installer/Installer.php',
	'LocalSettingsGenerator' => 'wiki/includes/installer/LocalSettingsGenerator.php',
	'MssqlInstaller' => 'wiki/includes/installer/MssqlInstaller.php',
	'MssqlUpdater' => 'wiki/includes/installer/MssqlUpdater.php',
	'MysqlInstaller' => 'wiki/includes/installer/MysqlInstaller.php',
	'MysqlUpdater' => 'wiki/includes/installer/MysqlUpdater.php',
	'OracleInstaller' => 'wiki/includes/installer/OracleInstaller.php',
	'OracleUpdater' => 'wiki/includes/installer/OracleUpdater.php',
	'PhpXmlBugTester' => 'wiki/includes/installer/PhpBugTests.php',
	'PostgresInstaller' => 'wiki/includes/installer/PostgresInstaller.php',
	'PostgresUpdater' => 'wiki/includes/installer/PostgresUpdater.php',
	'SqliteInstaller' => 'wiki/includes/installer/SqliteInstaller.php',
	'SqliteUpdater' => 'wiki/includes/installer/SqliteUpdater.php',
	'WebInstaller' => 'wiki/includes/installer/WebInstaller.php',
	'WebInstaller_Complete' => 'wiki/includes/installer/WebInstallerPage.php',
	'WebInstaller_Copying' => 'wiki/includes/installer/WebInstallerPage.php',
	'WebInstaller_DBConnect' => 'wiki/includes/installer/WebInstallerPage.php',
	'WebInstaller_DBSettings' => 'wiki/includes/installer/WebInstallerPage.php',
	'WebInstaller_Document' => 'wiki/includes/installer/WebInstallerPage.php',
	'WebInstaller_ExistingWiki' => 'wiki/includes/installer/WebInstallerPage.php',
	'WebInstaller_Install' => 'wiki/includes/installer/WebInstallerPage.php',
	'WebInstaller_Language' => 'wiki/includes/installer/WebInstallerPage.php',
	'WebInstaller_Name' => 'wiki/includes/installer/WebInstallerPage.php',
	'WebInstaller_Options' => 'wiki/includes/installer/WebInstallerPage.php',
	'WebInstaller_Readme' => 'wiki/includes/installer/WebInstallerPage.php',
	'WebInstaller_ReleaseNotes' => 'wiki/includes/installer/WebInstallerPage.php',
	'WebInstaller_Restart' => 'wiki/includes/installer/WebInstallerPage.php',
	'WebInstaller_Upgrade' => 'wiki/includes/installer/WebInstallerPage.php',
	'WebInstaller_UpgradeDoc' => 'wiki/includes/installer/WebInstallerPage.php',
	'WebInstaller_Welcome' => 'wiki/includes/installer/WebInstallerPage.php',
	'WebInstallerOutput' => 'wiki/includes/installer/WebInstallerOutput.php',
	'WebInstallerPage' => 'wiki/includes/installer/WebInstallerPage.php',

	# wiki/includes/job
	'IJobSpecification' => 'wiki/includes/jobqueue/JobSpecification.php',
	'Job' => 'wiki/includes/jobqueue/Job.php',
	'JobQueue' => 'wiki/includes/jobqueue/JobQueue.php',
	'JobQueueAggregator' => 'wiki/includes/jobqueue/aggregator/JobQueueAggregator.php',
	'JobQueueAggregatorMemc' => 'wiki/includes/jobqueue/aggregator/JobQueueAggregatorMemc.php',
	'JobQueueAggregatorRedis' => 'wiki/includes/jobqueue/aggregator/JobQueueAggregatorRedis.php',
	'JobQueueDB' => 'wiki/includes/jobqueue/JobQueueDB.php',
	'JobQueueConnectionError' => 'wiki/includes/jobqueue/JobQueue.php',
	'JobQueueError' => 'wiki/includes/jobqueue/JobQueue.php',
	'JobQueueGroup' => 'wiki/includes/jobqueue/JobQueueGroup.php',
	'JobQueueFederated' => 'wiki/includes/jobqueue/JobQueueFederated.php',
	'JobQueueRedis' => 'wiki/includes/jobqueue/JobQueueRedis.php',
	'JobSpecification' => 'wiki/includes/jobqueue/JobSpecification.php',

	# wiki/includes/jobqueue/jobs
	'DoubleRedirectJob' => 'wiki/includes/jobqueue/jobs/DoubleRedirectJob.php',
	'DuplicateJob' => 'wiki/includes/jobqueue/jobs/DuplicateJob.php',
	'EmaillingJob' => 'wiki/includes/jobqueue/jobs/EmaillingJob.php',
	'EnotifNotifyJob' => 'wiki/includes/jobqueue/jobs/EnotifNotifyJob.php',
	'HTMLCacheUpdateJob' => 'wiki/includes/jobqueue/jobs/HTMLCacheUpdateJob.php',
	'NullJob' => 'wiki/includes/jobqueue/jobs/NullJob.php',
	'RefreshLinksJob' => 'wiki/includes/jobqueue/jobs/RefreshLinksJob.php',
	'RefreshLinksJob2' => 'wiki/includes/jobqueue/jobs/RefreshLinksJob2.php',
	'UploadFromUrlJob' => 'wiki/includes/jobqueue/jobs/UploadFromUrlJob.php',
	'AssembleUploadChunksJob' => 'wiki/includes/jobqueue/jobs/AssembleUploadChunksJob.php',
	'PublishStashedFileJob' => 'wiki/includes/jobqueue/jobs/PublishStashedFileJob.php',

	# wiki/includes/jobqueue/utils
	'BacklinkJobUtils' => 'wiki/includes/jobqueue/utils/BacklinkJobUtils.php',

	# wiki/includes/json
	'FormatJson' => 'wiki/includes/json/FormatJson.php',

	# wiki/includes/libs
	'CSSJanus' => 'wiki/includes/libs/CSSJanus.php',
	'CSSJanus_Tokenizer' => 'wiki/includes/libs/CSSJanus.php',
	'CSSMin' => 'wiki/includes/libs/CSSMin.php',
	'GenericArrayObject' => 'wiki/includes/libs/GenericArrayObject.php',
	'HashRing' => 'wiki/includes/libs/HashRing.php',
	'HttpStatus' => 'wiki/includes/libs/HttpStatus.php',
	'IEContentAnalyzer' => 'wiki/includes/libs/IEContentAnalyzer.php',
	'IEUrlExtension' => 'wiki/includes/libs/IEUrlExtension.php',
	'MappedIterator' => 'wiki/includes/libs/MappedIterator.php',
	'JavaScriptMinifier' => 'wiki/includes/libs/JavaScriptMinifier.php',
	'JSCompilerContext' => 'wiki/includes/libs/jsminplus.php',
	'JSMinPlus' => 'wiki/includes/libs/jsminplus.php',
	'JSNode' => 'wiki/includes/libs/jsminplus.php',
	'JSParser' => 'wiki/includes/libs/jsminplus.php',
	'JSToken' => 'wiki/includes/libs/jsminplus.php',
	'JSTokenizer' => 'wiki/includes/libs/jsminplus.php',
	'MultiHttpClient' => 'wiki/includes/libs/MultiHttpClient.php',
	'MWMessagePack' => 'wiki/includes/libs/MWMessagePack.php',
	'ProcessCacheLRU' => 'wiki/includes/libs/ProcessCacheLRU.php',
	'RunningStat' => 'wiki/includes/libs/RunningStat.php',
	'ScopedCallback' => 'wiki/includes/libs/ScopedCallback.php',
	'ScopedPHPTimeout' => 'wiki/includes/libs/ScopedPHPTimeout.php',
	'XmlTypeCheck' => 'wiki/includes/libs/XmlTypeCheck.php',

	# wiki/includes/libs/lessphp
	'lessc' => 'wiki/includes/libs/lessc.inc.php',
	'lessc_parser' => 'wiki/includes/libs/lessc.inc.php',
	'lessc_formatter_classic' => 'wiki/includes/libs/lessc.inc.php',
	'lessc_formatter_compressed' => 'wiki/includes/libs/lessc.inc.php',
	'lessc_formatter_lessjs' => 'wiki/includes/libs/lessc.inc.php',

	# wiki/includes/logging
	'DatabaseLogEntry' => 'wiki/includes/logging/LogEntry.php',
	'DeleteLogFormatter' => 'wiki/includes/logging/DeleteLogFormatter.php',
	'LegacyLogFormatter' => 'wiki/includes/logging/LogFormatter.php',
	'LogEntry' => 'wiki/includes/logging/LogEntry.php',
	'LogEventsList' => 'wiki/includes/logging/LogEventsList.php',
	'LogEntryBase' => 'wiki/includes/logging/LogEntry.php',
	'LogFormatter' => 'wiki/includes/logging/LogFormatter.php',
	'LogPage' => 'wiki/includes/logging/LogPage.php',
	'LogPager' => 'wiki/includes/logging/LogPager.php',
	'ManualLogEntry' => 'wiki/includes/logging/LogEntry.php',
	'MoveLogFormatter' => 'wiki/includes/logging/MoveLogFormatter.php',
	'NewUsersLogFormatter' => 'wiki/includes/logging/NewUsersLogFormatter.php',
	'PatrolLog' => 'wiki/includes/logging/PatrolLog.php',
	'PatrolLogFormatter' => 'wiki/includes/logging/PatrolLogFormatter.php',
	'RCDatabaseLogEntry' => 'wiki/includes/logging/LogEntry.php',
	'RightsLogFormatter' => 'wiki/includes/logging/RightsLogFormatter.php',

	# Image gallery

	'ImageGallery' => 'wiki/includes/gallery/TraditionalImageGallery.php',
	'ImageGalleryBase' => 'wiki/includes/gallery/ImageGalleryBase.php',
	'NolinesImageGallery' => 'wiki/includes/gallery/NolinesImageGallery.php',
	'TraditionalImageGallery' => 'wiki/includes/gallery/TraditionalImageGallery.php',
	'PackedImageGallery' => 'wiki/includes/gallery/PackedImageGallery.php',
	'PackedHoverImageGallery' => 'wiki/includes/gallery/PackedOverlayImageGallery.php',
	'PackedOverlayImageGallery' => 'wiki/includes/gallery/PackedOverlayImageGallery.php',

	# wiki/includes/media
	'BitmapHandler' => 'wiki/includes/media/Bitmap.php',
	'BitmapHandler_ClientOnly' => 'wiki/includes/media/Bitmap_ClientOnly.php',
	'BitmapMetadataHandler' => 'wiki/includes/media/BitmapMetadataHandler.php',
	'BmpHandler' => 'wiki/includes/media/BMP.php',
	'DjVuHandler' => 'wiki/includes/media/DjVu.php',
	'DjVuImage' => 'wiki/includes/media/DjVuImage.php',
	'Exif' => 'wiki/includes/media/Exif.php',
	'ExifBitmapHandler' => 'wiki/includes/media/ExifBitmap.php',
	'FormatExif' => 'wiki/includes/media/FormatMetadata.php',
	'FormatMetadata' => 'wiki/includes/media/FormatMetadata.php',
	'GIFHandler' => 'wiki/includes/media/GIF.php',
	'GIFMetadataExtractor' => 'wiki/includes/media/GIFMetadataExtractor.php',
	'ImageHandler' => 'wiki/includes/media/ImageHandler.php',
	'IPTC' => 'wiki/includes/media/IPTC.php',
	'JpegHandler' => 'wiki/includes/media/Jpeg.php',
	'JpegMetadataExtractor' => 'wiki/includes/media/JpegMetadataExtractor.php',
	'MediaHandler' => 'wiki/includes/media/MediaHandler.php',
	'MediaTransformError' => 'wiki/includes/media/MediaTransformOutput.php',
	'MediaTransformOutput' => 'wiki/includes/media/MediaTransformOutput.php',
	'PNGHandler' => 'wiki/includes/media/PNG.php',
	'PNGMetadataExtractor' => 'wiki/includes/media/PNGMetadataExtractor.php',
	'SvgHandler' => 'wiki/includes/media/SVG.php',
	'SVGMetadataExtractor' => 'wiki/includes/media/SVGMetadataExtractor.php',
	'SVGReader' => 'wiki/includes/media/SVGMetadataExtractor.php',
	'ThumbnailImage' => 'wiki/includes/media/MediaTransformOutput.php',
	'TiffHandler' => 'wiki/includes/media/Tiff.php',
	'TransformParameterError' => 'wiki/includes/media/MediaTransformOutput.php',
	'XCFHandler' => 'wiki/includes/media/XCF.php',
	'XMPInfo' => 'wiki/includes/media/XMPInfo.php',
	'XMPReader' => 'wiki/includes/media/XMP.php',
	'XMPValidate' => 'wiki/includes/media/XMPValidate.php',

	# wiki/includes/normal
	'UtfNormal' => 'wiki/includes/normal/UtfNormal.php',

	# wiki/includes/objectcache
	'APCBagOStuff' => 'wiki/includes/objectcache/APCBagOStuff.php',
	'BagOStuff' => 'wiki/includes/objectcache/BagOStuff.php',
	'EmptyBagOStuff' => 'wiki/includes/objectcache/EmptyBagOStuff.php',
	'HashBagOStuff' => 'wiki/includes/objectcache/HashBagOStuff.php',
	'MediaWikiBagOStuff' => 'wiki/includes/objectcache/SqlBagOStuff.php',
	'MemCachedClientforWiki' => 'wiki/includes/objectcache/MemcachedClient.php',
	'MemcachedBagOStuff' => 'wiki/includes/objectcache/MemcachedBagOStuff.php',
	'MemcachedPeclBagOStuff' => 'wiki/includes/objectcache/MemcachedPeclBagOStuff.php',
	'MemcachedPhpBagOStuff' => 'wiki/includes/objectcache/MemcachedPhpBagOStuff.php',
	'MultiWriteBagOStuff' => 'wiki/includes/objectcache/MultiWriteBagOStuff.php',
	'MWMemcached' => 'wiki/includes/objectcache/MemcachedClient.php',
	'ObjectCache' => 'wiki/includes/objectcache/ObjectCache.php',
	'ObjectCacheSessionHandler' => 'wiki/includes/objectcache/ObjectCacheSessionHandler.php',
	'RedisBagOStuff' => 'wiki/includes/objectcache/RedisBagOStuff.php',
	'SqlBagOStuff' => 'wiki/includes/objectcache/SqlBagOStuff.php',
	'WinCacheBagOStuff' => 'wiki/includes/objectcache/WinCacheBagOStuff.php',
	'XCacheBagOStuff' => 'wiki/includes/objectcache/XCacheBagOStuff.php',

	# wiki/includes/parser
	'CacheTime' => 'wiki/includes/parser/CacheTime.php',
	'CoreParserFunctions' => 'wiki/includes/parser/CoreParserFunctions.php',
	'CoreTagHooks' => 'wiki/includes/parser/CoreTagHooks.php',
	'DateFormatter' => 'wiki/includes/parser/DateFormatter.php',
	'LinkHolderArray' => 'wiki/includes/parser/LinkHolderArray.php',
	'MWTidy' => 'wiki/includes/parser/Tidy.php',
	'MWTidyWrapper' => 'wiki/includes/parser/Tidy.php',
	'PPCustomFrame_DOM' => 'wiki/includes/parser/Preprocessor_DOM.php',
	'PPCustomFrame_Hash' => 'wiki/includes/parser/Preprocessor_Hash.php',
	'PPDAccum_Hash' => 'wiki/includes/parser/Preprocessor_Hash.php',
	'PPDPart' => 'wiki/includes/parser/Preprocessor_DOM.php',
	'PPDPart_Hash' => 'wiki/includes/parser/Preprocessor_Hash.php',
	'PPDStack' => 'wiki/includes/parser/Preprocessor_DOM.php',
	'PPDStackElement' => 'wiki/includes/parser/Preprocessor_DOM.php',
	'PPDStackElement_Hash' => 'wiki/includes/parser/Preprocessor_Hash.php',
	'PPDStack_Hash' => 'wiki/includes/parser/Preprocessor_Hash.php',
	'PPFrame' => 'wiki/includes/parser/Preprocessor.php',
	'PPFrame_DOM' => 'wiki/includes/parser/Preprocessor_DOM.php',
	'PPFrame_Hash' => 'wiki/includes/parser/Preprocessor_Hash.php',
	'PPNode' => 'wiki/includes/parser/Preprocessor.php',
	'PPNode_DOM' => 'wiki/includes/parser/Preprocessor_DOM.php',
	'PPNode_Hash_Array' => 'wiki/includes/parser/Preprocessor_Hash.php',
	'PPNode_Hash_Attr' => 'wiki/includes/parser/Preprocessor_Hash.php',
	'PPNode_Hash_Text' => 'wiki/includes/parser/Preprocessor_Hash.php',
	'PPNode_Hash_Tree' => 'wiki/includes/parser/Preprocessor_Hash.php',
	'PPTemplateFrame_DOM' => 'wiki/includes/parser/Preprocessor_DOM.php',
	'PPTemplateFrame_Hash' => 'wiki/includes/parser/Preprocessor_Hash.php',
	'Parser' => 'wiki/includes/parser/Parser.php',
	'ParserCache' => 'wiki/includes/parser/ParserCache.php',
	'ParserOptions' => 'wiki/includes/parser/ParserOptions.php',
	'ParserOutput' => 'wiki/includes/parser/ParserOutput.php',
	'Parser_DiffTest' => 'wiki/includes/parser/Parser_DiffTest.php',
	'Preprocessor' => 'wiki/includes/parser/Preprocessor.php',
	'Preprocessor_DOM' => 'wiki/includes/parser/Preprocessor_DOM.php',
	'Preprocessor_Hash' => 'wiki/includes/parser/Preprocessor_Hash.php',
	'StripState' => 'wiki/includes/parser/StripState.php',

	# wiki/includes/profiler
	'Profiler' => 'wiki/includes/profiler/Profiler.php',
	'ProfilerMwprof' => 'wiki/includes/profiler/ProfilerMwprof.php',
	'ProfilerSimple' => 'wiki/includes/profiler/ProfilerSimple.php',
	'ProfilerSimpleText' => 'wiki/includes/profiler/ProfilerSimpleText.php',
	'ProfilerSimpleTrace' => 'wiki/includes/profiler/ProfilerSimpleTrace.php',
	'ProfilerSimpleUDP' => 'wiki/includes/profiler/ProfilerSimpleUDP.php',
	'ProfilerStub' => 'wiki/includes/profiler/ProfilerStub.php',
	'ProfileSection' => 'wiki/includes/profiler/Profiler.php',

	# wiki/includes/rcfeed
	'RCFeedEngine' => 'wiki/includes/rcfeed/RCFeedEngine.php',
	'RedisPubSubFeedEngine' => 'wiki/includes/rcfeed/RedisPubSubFeedEngine.php',
	'UDPRCFeedEngine' => 'wiki/includes/rcfeed/UDPRCFeedEngine.php',
	'RCFeedFormatter' => 'wiki/includes/rcfeed/RCFeedFormatter.php',
	'IRCColourfulRCFeedFormatter' => 'wiki/includes/rcfeed/IRCColourfulRCFeedFormatter.php',
	'JSONRCFeedFormatter' => 'wiki/includes/rcfeed/JSONRCFeedFormatter.php',
	'XMLRCFeedFormatter' => 'wiki/includes/rcfeed/XMLRCFeedFormatter.php',
	'MachineReadableRCFeedFormatter' => 'wiki/includes/rcfeed/MachineReadableRCFeedFormatter.php',

	# wiki/includes/resourceloader
	'ResourceLoader' => 'wiki/includes/resourceloader/ResourceLoader.php',
	'ResourceLoaderContext' => 'wiki/includes/resourceloader/ResourceLoaderContext.php',
	'ResourceLoaderFileModule' => 'wiki/includes/resourceloader/ResourceLoaderFileModule.php',
	'ResourceLoaderFilePageModule' => 'wiki/includes/resourceloader/ResourceLoaderFilePageModule.php',
	'ResourceLoaderLESSFunctions' => 'wiki/includes/resourceloader/ResourceLoaderLESSFunctions.php',
	'ResourceLoaderModule' => 'wiki/includes/resourceloader/ResourceLoaderModule.php',
	'ResourceLoaderNoscriptModule' => 'wiki/includes/resourceloader/ResourceLoaderNoscriptModule.php',
	'ResourceLoaderSiteModule' => 'wiki/includes/resourceloader/ResourceLoaderSiteModule.php',
	'ResourceLoaderStartUpModule' => 'wiki/includes/resourceloader/ResourceLoaderStartUpModule.php',
	'ResourceLoaderUserCSSPrefsModule' =>
		'wiki/includes/resourceloader/ResourceLoaderUserCSSPrefsModule.php',
	'ResourceLoaderUserGroupsModule' => 'wiki/includes/resourceloader/ResourceLoaderUserGroupsModule.php',
	'ResourceLoaderUserModule' => 'wiki/includes/resourceloader/ResourceLoaderUserModule.php',
	'ResourceLoaderUserOptionsModule' => 'wiki/includes/resourceloader/ResourceLoaderUserOptionsModule.php',
	'ResourceLoaderUserTokensModule' => 'wiki/includes/resourceloader/ResourceLoaderUserTokensModule.php',
	'ResourceLoaderLanguageDataModule' =>
		'wiki/includes/resourceloader/ResourceLoaderLanguageDataModule.php',
	'ResourceLoaderWikiModule' => 'wiki/includes/resourceloader/ResourceLoaderWikiModule.php',

	# wiki/includes/revisiondelete
	'RevDel_ArchivedFileItem' => 'wiki/includes/revisiondelete/RevisionDelete.php',
	'RevDel_ArchivedFileList' => 'wiki/includes/revisiondelete/RevisionDelete.php',
	'RevDel_ArchivedRevisionItem' => 'wiki/includes/revisiondelete/RevisionDelete.php',
	'RevDel_ArchiveItem' => 'wiki/includes/revisiondelete/RevisionDelete.php',
	'RevDel_ArchiveList' => 'wiki/includes/revisiondelete/RevisionDelete.php',
	'RevDel_FileItem' => 'wiki/includes/revisiondelete/RevisionDelete.php',
	'RevDel_FileList' => 'wiki/includes/revisiondelete/RevisionDelete.php',
	'RevDel_Item' => 'wiki/includes/revisiondelete/RevisionDeleteAbstracts.php',
	'RevDel_List' => 'wiki/includes/revisiondelete/RevisionDeleteAbstracts.php',
	'RevDel_LogItem' => 'wiki/includes/revisiondelete/RevisionDelete.php',
	'RevDel_LogList' => 'wiki/includes/revisiondelete/RevisionDelete.php',
	'RevDel_RevisionItem' => 'wiki/includes/revisiondelete/RevisionDelete.php',
	'RevDel_RevisionList' => 'wiki/includes/revisiondelete/RevisionDelete.php',
	'RevisionDeleter' => 'wiki/includes/revisiondelete/RevisionDeleter.php',
	'RevisionDeleteUser' => 'wiki/includes/revisiondelete/RevisionDeleteUser.php',

	# wiki/includes/search
	'MssqlSearchResultSet' => 'wiki/includes/search/SearchMssql.php',
	'MySQLSearchResultSet' => 'wiki/includes/search/SearchMySQL.php',
	'PostgresSearchResult' => 'wiki/includes/search/SearchPostgres.php',
	'PostgresSearchResultSet' => 'wiki/includes/search/SearchPostgres.php',
	'SearchDatabase' => 'wiki/includes/search/SearchDatabase.php',
	'SearchEngine' => 'wiki/includes/search/SearchEngine.php',
	'SearchEngineDummy' => 'wiki/includes/search/SearchEngine.php',
	'SearchHighlighter' => 'wiki/includes/search/SearchHighlighter.php',
	'SearchMssql' => 'wiki/includes/search/SearchMssql.php',
	'SearchMySQL' => 'wiki/includes/search/SearchMySQL.php',
	'SearchNearMatchResultSet' => 'wiki/includes/search/SearchResultSet.php',
	'SearchOracle' => 'wiki/includes/search/SearchOracle.php',
	'SearchPostgres' => 'wiki/includes/search/SearchPostgres.php',
	'SearchResult' => 'wiki/includes/search/SearchResult.php',
	'SearchResultSet' => 'wiki/includes/search/SearchResultSet.php',
	'SearchResultTooMany' => 'wiki/includes/search/SearchEngine.php',
	'SearchSqlite' => 'wiki/includes/search/SearchSqlite.php',
	'SqliteSearchResultSet' => 'wiki/includes/search/SearchSqlite.php',
	'SqlSearchResultSet' => 'wiki/includes/search/SearchResultSet.php',

	# wiki/includes/site
	'MediaWikiSite' => 'wiki/includes/site/MediaWikiSite.php',
	'Site' => 'wiki/includes/site/Site.php',
	'SiteObject' => 'wiki/includes/site/Site.php',
	'SiteArray' => 'wiki/includes/site/SiteList.php',
	'SiteList' => 'wiki/includes/site/SiteList.php',
	'SiteSQLStore' => 'wiki/includes/site/SiteSQLStore.php',
	'Sites' => 'wiki/includes/site/SiteSQLStore.php',
	'SiteStore' => 'wiki/includes/site/SiteStore.php',

	# wiki/includes/specialpage
	'ChangesListSpecialPage' => 'wiki/includes/specialpage/ChangesListSpecialPage.php',
	'FormSpecialPage' => 'wiki/includes/specialpage/FormSpecialPage.php',
	'IncludableSpecialPage' => 'wiki/includes/specialpage/IncludableSpecialPage.php',
	'RedirectSpecialArticle' => 'wiki/includes/specialpage/RedirectSpecialPage.php',
	'RedirectSpecialPage' => 'wiki/includes/specialpage/RedirectSpecialPage.php',
	'SpecialPage' => 'wiki/includes/specialpage/SpecialPage.php',
	'SpecialPageFactory' => 'wiki/includes/specialpage/SpecialPageFactory.php',
	'SpecialRedirectToSpecial' => 'wiki/includes/specialpage/RedirectSpecialPage.php',
	'UnlistedSpecialPage' => 'wiki/includes/specialpage/UnlistedSpecialPage.php',

	# wiki/includes/specials
	'ActiveUsersPager' => 'wiki/includes/specials/SpecialActiveusers.php',
	'AllmessagesTablePager' => 'wiki/includes/specials/SpecialAllmessages.php',
	'AncientPagesPage' => 'wiki/includes/specials/SpecialAncientpages.php',
	'BlockListPager' => 'wiki/includes/specials/SpecialBlockList.php',
	'BrokenRedirectsPage' => 'wiki/includes/specials/SpecialBrokenRedirects.php',
	'CategoryPager' => 'wiki/includes/specials/SpecialCategories.php',
	'ContribsPager' => 'wiki/includes/specials/SpecialContributions.php',
	'DeadendPagesPage' => 'wiki/includes/specials/SpecialDeadendpages.php',
	'DeletedContribsPager' => 'wiki/includes/specials/SpecialDeletedContributions.php',
	'DeletedContributionsPage' => 'wiki/includes/specials/SpecialDeletedContributions.php',
	'DoubleRedirectsPage' => 'wiki/includes/specials/SpecialDoubleRedirects.php',
	'EditWatchlistCheckboxSeriesField' => 'wiki/includes/specials/SpecialEditWatchlist.php',
	'EditWatchlistNormalHTMLForm' => 'wiki/includes/specials/SpecialEditWatchlist.php',
	'EmailConfirmation' => 'wiki/includes/specials/SpecialConfirmemail.php',
	'EmailInvalidation' => 'wiki/includes/specials/SpecialConfirmemail.php',
	'FewestrevisionsPage' => 'wiki/includes/specials/SpecialFewestrevisions.php',
	'FileDuplicateSearchPage' => 'wiki/includes/specials/SpecialFileDuplicateSearch.php',
	'HTMLBlockedUsersItemSelect' => 'wiki/includes/specials/SpecialBlockList.php',
	'ImageListPager' => 'wiki/includes/specials/SpecialListfiles.php',
	'ImportReporter' => 'wiki/includes/specials/SpecialImport.php',
	'IPBlockForm' => 'wiki/includes/specials/SpecialBlock.php',
	'LinkSearchPage' => 'wiki/includes/specials/SpecialLinkSearch.php',
	'ListredirectsPage' => 'wiki/includes/specials/SpecialListredirects.php',
	'ListDuplicatedFilesPage' => 'wiki/includes/specials/SpecialListDuplicatedFiles.php',
	'LoginForm' => 'wiki/includes/specials/SpecialUserlogin.php',
	'LonelyPagesPage' => 'wiki/includes/specials/SpecialLonelypages.php',
	'LongPagesPage' => 'wiki/includes/specials/SpecialLongpages.php',
	'MergeHistoryPager' => 'wiki/includes/specials/SpecialMergeHistory.php',
	'MIMEsearchPage' => 'wiki/includes/specials/SpecialMIMEsearch.php',
	'MostcategoriesPage' => 'wiki/includes/specials/SpecialMostcategories.php',
	'MostimagesPage' => 'wiki/includes/specials/SpecialMostimages.php',
	'MostinterwikisPage' => 'wiki/includes/specials/SpecialMostinterwikis.php',
	'MostlinkedCategoriesPage' => 'wiki/includes/specials/SpecialMostlinkedcategories.php',
	'MostlinkedPage' => 'wiki/includes/specials/SpecialMostlinked.php',
	'MostlinkedTemplatesPage' => 'wiki/includes/specials/SpecialMostlinkedtemplates.php',
	'MostrevisionsPage' => 'wiki/includes/specials/SpecialMostrevisions.php',
	'MovePageForm' => 'wiki/includes/specials/SpecialMovepage.php',
	'NewFilesPager' => 'wiki/includes/specials/SpecialNewimages.php',
	'NewPagesPager' => 'wiki/includes/specials/SpecialNewpages.php',
	'PageArchive' => 'wiki/includes/specials/SpecialUndelete.php',
	'PopularPagesPage' => 'wiki/includes/specials/SpecialPopularpages.php',
	'ProtectedPagesPager' => 'wiki/includes/specials/SpecialProtectedpages.php',
	'ProtectedTitlesPager' => 'wiki/includes/specials/SpecialProtectedtitles.php',
	'RandomPage' => 'wiki/includes/specials/SpecialRandompage.php',
	'ShortPagesPage' => 'wiki/includes/specials/SpecialShortpages.php',
	'SpecialActiveUsers' => 'wiki/includes/specials/SpecialActiveusers.php',
	'SpecialAllmessages' => 'wiki/includes/specials/SpecialAllmessages.php',
	'SpecialAllMyUploads' => 'wiki/includes/specials/SpecialMyRedirectPages.php',
	'SpecialAllpages' => 'wiki/includes/specials/SpecialAllpages.php',
	'SpecialBlankpage' => 'wiki/includes/specials/SpecialBlankpage.php',
	'SpecialBlock' => 'wiki/includes/specials/SpecialBlock.php',
	'SpecialBlockList' => 'wiki/includes/specials/SpecialBlockList.php',
	'SpecialBookSources' => 'wiki/includes/specials/SpecialBooksources.php',
	'SpecialCachedPage' => 'wiki/includes/specials/SpecialCachedPage.php',
	'SpecialCategories' => 'wiki/includes/specials/SpecialCategories.php',
	'SpecialChangeEmail' => 'wiki/includes/specials/SpecialChangeEmail.php',
	'SpecialChangePassword' => 'wiki/includes/specials/SpecialChangePassword.php',
	'SpecialComparePages' => 'wiki/includes/specials/SpecialComparePages.php',
	'SpecialContributions' => 'wiki/includes/specials/SpecialContributions.php',
	'SpecialCreateAccount' => 'wiki/includes/specials/SpecialCreateAccount.php',
	'SpecialDiff' => 'wiki/includes/specials/SpecialDiff.php',
	'SpecialEditWatchlist' => 'wiki/includes/specials/SpecialEditWatchlist.php',
	'SpecialEmailUser' => 'wiki/includes/specials/SpecialEmailuser.php',
	'SpecialExpandTemplates' => 'wiki/includes/specials/SpecialExpandTemplates.php',
	'SpecialExport' => 'wiki/includes/specials/SpecialExport.php',
	'SpecialFilepath' => 'wiki/includes/specials/SpecialFilepath.php',
	'SpecialImport' => 'wiki/includes/specials/SpecialImport.php',
	'SpecialJavaScriptTest' => 'wiki/includes/specials/SpecialJavaScriptTest.php',
	'SpecialListAdmins' => 'wiki/includes/specials/SpecialListusers.php',
	'SpecialListBots' => 'wiki/includes/specials/SpecialListusers.php',
	'SpecialListFiles' => 'wiki/includes/specials/SpecialListfiles.php',
	'SpecialListGroupRights' => 'wiki/includes/specials/SpecialListgrouprights.php',
	'SpecialListUsers' => 'wiki/includes/specials/SpecialListusers.php',
	'SpecialLockdb' => 'wiki/includes/specials/SpecialLockdb.php',
	'SpecialLog' => 'wiki/includes/specials/SpecialLog.php',
	'SpecialMergeHistory' => 'wiki/includes/specials/SpecialMergeHistory.php',
	'SpecialMycontributions' => 'wiki/includes/specials/SpecialMyRedirectPages.php',
	'SpecialMypage' => 'wiki/includes/specials/SpecialMyRedirectPages.php',
	'SpecialMytalk' => 'wiki/includes/specials/SpecialMyRedirectPages.php',
	'SpecialMyuploads' => 'wiki/includes/specials/SpecialMyRedirectPages.php',
	'SpecialNewFiles' => 'wiki/includes/specials/SpecialNewimages.php',
	'SpecialNewpages' => 'wiki/includes/specials/SpecialNewpages.php',
	'SpecialPasswordReset' => 'wiki/includes/specials/SpecialPasswordReset.php',
	'SpecialPagesWithProp' => 'wiki/includes/specials/SpecialPagesWithProp.php',
	'SpecialPermanentLink' => 'wiki/includes/specials/SpecialPermanentLink.php',
	'SpecialPreferences' => 'wiki/includes/specials/SpecialPreferences.php',
	'SpecialPrefixindex' => 'wiki/includes/specials/SpecialPrefixindex.php',
	'SpecialProtectedpages' => 'wiki/includes/specials/SpecialProtectedpages.php',
	'SpecialProtectedtitles' => 'wiki/includes/specials/SpecialProtectedtitles.php',
	'SpecialRandomInCategory' => 'wiki/includes/specials/SpecialRandomInCategory.php',
	'SpecialRandomredirect' => 'wiki/includes/specials/SpecialRandomredirect.php',
	'SpecialRecentChanges' => 'wiki/includes/specials/SpecialRecentchanges.php',
	'SpecialRecentChangesLinked' => 'wiki/includes/specials/SpecialRecentchangeslinked.php',
	'SpecialRedirect' => 'wiki/includes/specials/SpecialRedirect.php',
	'SpecialResetTokens' => 'wiki/includes/specials/SpecialResetTokens.php',
	'SpecialRevisionDelete' => 'wiki/includes/specials/SpecialRevisiondelete.php',
	'SpecialRunJobs' => 'wiki/includes/specials/SpecialRunJobs.php',
	'SpecialSearch' => 'wiki/includes/specials/SpecialSearch.php',
	'SpecialSpecialpages' => 'wiki/includes/specials/SpecialSpecialpages.php',
	'SpecialStatistics' => 'wiki/includes/specials/SpecialStatistics.php',
	'SpecialTags' => 'wiki/includes/specials/SpecialTags.php',
	'SpecialTrackingCategories' => 'wiki/includes/specials/SpecialTrackingCategories.php',
	'SpecialUnblock' => 'wiki/includes/specials/SpecialUnblock.php',
	'SpecialUndelete' => 'wiki/includes/specials/SpecialUndelete.php',
	'SpecialUnlockdb' => 'wiki/includes/specials/SpecialUnlockdb.php',
	'SpecialUpload' => 'wiki/includes/specials/SpecialUpload.php',
	'SpecialUploadStash' => 'wiki/includes/specials/SpecialUploadStash.php',
	'SpecialUploadStashTooLargeException' => 'wiki/includes/specials/SpecialUploadStash.php',
	'SpecialUserlogout' => 'wiki/includes/specials/SpecialUserlogout.php',
	'SpecialVersion' => 'wiki/includes/specials/SpecialVersion.php',
	'SpecialWatchlist' => 'wiki/includes/specials/SpecialWatchlist.php',
	'SpecialWhatLinksHere' => 'wiki/includes/specials/SpecialWhatlinkshere.php',
	'UncategorizedCategoriesPage' => 'wiki/includes/specials/SpecialUncategorizedcategories.php',
	'UncategorizedImagesPage' => 'wiki/includes/specials/SpecialUncategorizedimages.php',
	'UncategorizedPagesPage' => 'wiki/includes/specials/SpecialUncategorizedpages.php',
	'UncategorizedTemplatesPage' => 'wiki/includes/specials/SpecialUncategorizedtemplates.php',
	'UnusedCategoriesPage' => 'wiki/includes/specials/SpecialUnusedcategories.php',
	'UnusedimagesPage' => 'wiki/includes/specials/SpecialUnusedimages.php',
	'UnusedtemplatesPage' => 'wiki/includes/specials/SpecialUnusedtemplates.php',
	'UnwatchedpagesPage' => 'wiki/includes/specials/SpecialUnwatchedpages.php',
	'UploadChunkFileException' => 'wiki/includes/upload/UploadFromChunks.php',
	'UploadChunkZeroLengthFileException' => 'wiki/includes/upload/UploadFromChunks.php',
	'UploadChunkVerificationException' => 'wiki/includes/upload/UploadFromChunks.php',
	'UploadForm' => 'wiki/includes/specials/SpecialUpload.php',
	'UploadSourceField' => 'wiki/includes/specials/SpecialUpload.php',
	'UserrightsPage' => 'wiki/includes/specials/SpecialUserrights.php',
	'UsersPager' => 'wiki/includes/specials/SpecialListusers.php',
	'WantedCategoriesPage' => 'wiki/includes/specials/SpecialWantedcategories.php',
	'WantedFilesPage' => 'wiki/includes/specials/SpecialWantedfiles.php',
	'WantedPagesPage' => 'wiki/includes/specials/SpecialWantedpages.php',
	'WantedTemplatesPage' => 'wiki/includes/specials/SpecialWantedtemplates.php',
	'WatchlistEditor' => 'wiki/includes/specials/SpecialEditWatchlist.php',
	'WithoutInterwikiPage' => 'wiki/includes/specials/SpecialWithoutinterwiki.php',

	# wiki/includes/templates
	'UserloginTemplate' => 'wiki/includes/templates/Userlogin.php',
	'UsercreateTemplate' => 'wiki/includes/templates/Usercreate.php',

	# wiki/includes/title
	'PageLinkRenderer' => 'wiki/includes/title/PageLinkRenderer.php',
	'TitleFormatter' => 'wiki/includes/title/TitleFormatter.php',
	'TitleParser' => 'wiki/includes/title/TitleParser.php',
	'TitleValue' => 'wiki/includes/title/TitleValue.php',
	'MalformedTitleException' => 'wiki/includes/title/MalformedTitleException.php',
	'MediaWikiPageLinkRenderer' => 'wiki/includes/title/MediaWikiPageLinkRenderer.php',
	'MediaWikiTitleCodec' => 'wiki/includes/title/MediaWikiTitleCodec.php',

	# wiki/includes/upload
	'UploadBase' => 'wiki/includes/upload/UploadBase.php',
	'UploadFromFile' => 'wiki/includes/upload/UploadFromFile.php',
	'UploadFromChunks' => 'wiki/includes/upload/UploadFromChunks.php',
	'UploadFromStash' => 'wiki/includes/upload/UploadFromStash.php',
	'UploadFromUrl' => 'wiki/includes/upload/UploadFromUrl.php',
	'UploadStash' => 'wiki/includes/upload/UploadStash.php',
	'UploadStashBadPathException' => 'wiki/includes/upload/UploadStash.php',
	'UploadStashException' => 'wiki/includes/upload/UploadStash.php',
	'UploadStashFile' => 'wiki/includes/upload/UploadStash.php',
	'UploadStashFileException' => 'wiki/includes/upload/UploadStash.php',
	'UploadStashFileNotFoundException' => 'wiki/includes/upload/UploadStash.php',
	'UploadStashNotAvailableException' => 'wiki/includes/upload/UploadStash.php',
	'UploadStashZeroLengthFileException' => 'wiki/includes/upload/UploadStash.php',
	'UploadStashNotLoggedInException' => 'wiki/includes/upload/UploadStash.php',
	'UploadStashWrongOwnerException' => 'wiki/includes/upload/UploadStash.php',
	'UploadStashNoSuchKeyException' => 'wiki/includes/upload/UploadStash.php',

	# wiki/includes/utils
	'ArrayUtils' => 'wiki/includes/utils/ArrayUtils.php',
	'CdbException' => 'wiki/includes/utils/Cdb.php',
	'CdbFunctions' => 'wiki/includes/utils/CdbPHP.php',
	'CdbReader' => 'wiki/includes/utils/Cdb.php',
	'CdbReaderDBA' => 'wiki/includes/utils/CdbDBA.php',
	'CdbReaderPHP' => 'wiki/includes/utils/CdbPHP.php',
	'CdbWriter' => 'wiki/includes/utils/Cdb.php',
	'CdbWriterDBA' => 'wiki/includes/utils/CdbDBA.php',
	'CdbWriterPHP' => 'wiki/includes/utils/CdbPHP.php',
	'ConfEditor' => 'wiki/includes/utils/ConfEditor.php',
	'ConfEditorParseError' => 'wiki/includes/utils/ConfEditor.php',
	'ConfEditorToken' => 'wiki/includes/utils/ConfEditor.php',
	'DoubleReplacer' => 'wiki/includes/utils/StringUtils.php',
	'ExplodeIterator' => 'wiki/includes/utils/StringUtils.php',
	'HashtableReplacer' => 'wiki/includes/utils/StringUtils.php',
	'IP' => 'wiki/includes/utils/IP.php',
	'MWCryptRand' => 'wiki/includes/utils/MWCryptRand.php',
	'MWFunction' => 'wiki/includes/utils/MWFunction.php',
	'RegexlikeReplacer' => 'wiki/includes/utils/StringUtils.php',
	'ReplacementArray' => 'wiki/includes/utils/StringUtils.php',
	'Replacer' => 'wiki/includes/utils/StringUtils.php',
	'StringUtils' => 'wiki/includes/utils/StringUtils.php',
	'UIDGenerator' => 'wiki/includes/utils/UIDGenerator.php',
	'ZipDirectoryReader' => 'wiki/includes/utils/ZipDirectoryReader.php',
	'ZipDirectoryReaderError' => 'wiki/includes/utils/ZipDirectoryReader.php',

	# languages
	'ConverterRule' => 'wiki/languages/ConverterRule.php',
	'FakeConverter' => 'wiki/languages/Language.php',
	'Language' => 'wiki/languages/Language.php',
	'LanguageConverter' => 'wiki/languages/LanguageConverter.php',
	'CLDRPluralRuleConverter' => 'wiki/languages/utils/CLDRPluralRuleConverter.php',
	'CLDRPluralRuleConverter_Expression' => 'wiki/languages/utils/CLDRPluralRuleConverter_Expression.php',
	'CLDRPluralRuleConverter_Fragment' => 'wiki/languages/utils/CLDRPluralRuleConverter_Fragment.php',
	'CLDRPluralRuleConverter_Operator' => 'wiki/languages/utils/CLDRPluralRuleConverter_Operator.php',
	'CLDRPluralRuleEvaluator' => 'wiki/languages/utils/CLDRPluralRuleEvaluator.php',
	'CLDRPluralRuleEvaluator_Range' => 'wiki/languages/utils/CLDRPluralRuleEvaluator_Range.php',
	'CLDRPluralRuleError' => 'wiki/languages/utils/CLDRPluralRuleError.php',

	# maintenance
	'BackupDumper' => 'wiki/maintenance/backup.inc',
	'ConvertLinks' => 'wiki/maintenance/convertLinks.php',
	'DeleteArchivedFilesImplementation' => 'wiki/maintenance/deleteArchivedFiles.inc',
	'DeleteArchivedRevisionsImplementation' => 'wiki/maintenance/deleteArchivedRevisions.inc',
	'DeleteDefaultMessages' => 'wiki/maintenance/deleteDefaultMessages.php',
	'DumpDBZip2Output' => 'wiki/maintenance/backup.inc',
	'ExportProgressFilter' => 'wiki/maintenance/backup.inc',
	'FakeMaintenance' => 'wiki/maintenance/Maintenance.php',
	'FixExtLinksProtocolRelative' => 'wiki/maintenance/fixExtLinksProtocolRelative.php',
	'LoggedUpdateMaintenance' => 'wiki/maintenance/Maintenance.php',
	'Maintenance' => 'wiki/maintenance/Maintenance.php',
	'PopulateCategory' => 'wiki/maintenance/populateCategory.php',
	'PopulateImageSha1' => 'wiki/maintenance/populateImageSha1.php',
	'PopulateFilearchiveSha1' => 'wiki/maintenance/populateFilearchiveSha1.php',
	'PopulateLogSearch' => 'wiki/maintenance/populateLogSearch.php',
	'PopulateLogUsertext' => 'wiki/maintenance/populateLogUsertext.php',
	'PopulateParentId' => 'wiki/maintenance/populateParentId.php',
	'PopulateRevisionLength' => 'wiki/maintenance/populateRevisionLength.php',
	'PopulateRevisionSha1' => 'wiki/maintenance/populateRevisionSha1.php',
	'RefreshLinks' => 'wiki/maintenance/refreshLinks.php',
	'SevenZipStream' => 'wiki/maintenance/7zip.inc',
	'Sqlite' => 'wiki/maintenance/sqlite.inc',
	'UpdateCollation' => 'wiki/maintenance/updateCollation.php',
	'UpdateRestrictions' => 'wiki/maintenance/updateRestrictions.php',
	'UserDupes' => 'wiki/maintenance/userDupes.inc',

	# wiki/maintenance/language
	'CsvStatsOutput' => 'wiki/maintenance/language/StatOutputs.php',
	'ExtensionLanguages' => 'wiki/maintenance/language/languages.inc',
	'Languages' => 'wiki/maintenance/language/languages.inc',
	'MessageWriter' => 'wiki/maintenance/language/writeMessagesArray.inc',
	'StatsOutput' => 'wiki/maintenance/language/StatOutputs.php',
	'TextStatsOutput' => 'wiki/maintenance/language/StatOutputs.php',
	'WikiStatsOutput' => 'wiki/maintenance/language/StatOutputs.php',

	# wiki/maintenance/term
	'AnsiTermColorer' => 'wiki/maintenance/term/MWTerm.php',
	'DummyTermColorer' => 'wiki/maintenance/term/MWTerm.php',

	# mw-config
	'InstallerOverrides' => 'wiki/mw-config/overrides.php',
	'MyLocalSettingsGenerator' => 'wiki/mw-config/overrides.php',

	# skins
	'CologneBlueTemplate' => 'wiki/skins/CologneBlue.php',
	'ModernTemplate' => 'wiki/skins/Modern.php',
	'MonoBookTemplate' => 'wiki/skins/MonoBook.php',
	'SkinCologneBlue' => 'wiki/skins/CologneBlue.php',
	'SkinModern' => 'wiki/skins/Modern.php',
	'SkinMonoBook' => 'wiki/skins/MonoBook.php',
	'SkinVector' => 'wiki/skins/Vector.php',
	'VectorTemplate' => 'wiki/skins/Vector.php',
);

class AutoLoader {
	static protected $autoloadLocalClassesLower = null;

	/**
	 * autoload - take a class name and attempt to load it
	 *
	 * @param string $className name of class we're looking for.
	 */
	static function autoload( $className ) {
		global $wgAutoloadClasses, $wgAutoloadLocalClasses,
			$wgAutoloadAttemptLowercase;

		// Workaround for PHP bug <https://bugs.php.net/bug.php?id=49143> (5.3.2. is broken, it's
		// fixed in 5.3.6). Strip leading backslashes from class names. When namespaces are used,
		// leading backslashes are used to indicate the top-level namespace, e.g. \foo\Bar. When
		// used like this in the code, the leading backslash isn't passed to the auto-loader
		// ($className would be 'foo\Bar'). However, if a class is accessed using a string instead
		// of a class literal (e.g. $class = '\foo\Bar'; new $class()), then some versions of PHP
		// do not strip the leading backlash in this case, causing autoloading to fail.
		$className = ltrim( $className, '\\' );

		$filename = false;

		if ( isset( $wgAutoloadLocalClasses[$className] ) ) {
			$filename = $wgAutoloadLocalClasses[$className];
		} elseif ( isset( $wgAutoloadClasses[$className] ) ) {
			$filename = $wgAutoloadClasses[$className];
		} elseif ( $wgAutoloadAttemptLowercase ) {
			/*
			 * Try a different capitalisation.
			 *
			 * PHP 4 objects are always serialized with the classname coerced to lowercase,
			 * and we are plagued with several legacy uses created by MediaWiki < 1.5, see
			 * https://wikitech.wikimedia.org/wiki/Text_storage_data
			 */
			$lowerClass = strtolower( $className );

			if ( self::$autoloadLocalClassesLower === null ) {
				self::$autoloadLocalClassesLower = array_change_key_case( $wgAutoloadLocalClasses, CASE_LOWER );
			}

			if ( isset( self::$autoloadLocalClassesLower[$lowerClass] ) ) {
				if ( function_exists( 'wfDebugLog' ) ) {
					wfDebugLog( 'autoloader', "Class {$className} was loaded using incorrect case" );
				}
				$filename = self::$autoloadLocalClassesLower[$lowerClass];
			}
		}

		if ( !$filename ) {
			// Class not found; let the next autoloader try to find it
			return;
		}

		// Make an absolute path, this improves performance by avoiding some stat calls
		if ( substr( $filename, 0, 1 ) != '/' && substr( $filename, 1, 1 ) != ':' ) {
			global $IP;
			$filename = "$IP/wiki/$filename";
		}

		require $filename;
	}

	/**
	 * Force a class to be run through the autoloader, helpful for things like
	 * Sanitizer that have define()s outside of their class definition. Of course
	 * this wouldn't be necessary if everything in MediaWiki was class-based. Sigh.
	 *
	 * @param $class string
	 * @return Boolean Return the results of class_exists() so we know if we were successful
	 */
	static function loadClass( $class ) {
		return class_exists( $class );
	}

	/**
	 * Method to clear the protected class property $autoloadLocalClassesLower.
	 * Used in tests.
	 */
	static function resetAutoloadLocalClassesLower() {
		self::$autoloadLocalClassesLower = null;
	}
}

spl_autoload_register( array( 'AutoLoader', 'autoload' ) );
